package io.crowdcode.scrumr.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class UserEditComponent extends CustomComponent
{

	private static final long serialVersionUID = 1L;
	
	@AutoGenerated
	private Label lblEmail;
	
	@AutoGenerated
	private TextField txtEmail;

	public UserEditComponent()
	{
		GridLayout gridLayout = new GridLayout(2,5);
		setCompositionRoot(gridLayout);
		
		lblEmail = new Label("Email");
		txtEmail = new TextField();
		
		gridLayout.addComponent(lblEmail);
		gridLayout.addComponent(txtEmail);
	}


}
